version: '2.2'

networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: wireless-sensor

#volumes:
#  config:

services:
  broker:
    image: docker.io/eclipse-mosquitto:latest
    user: mosquitto
    read_only: yes
    #ports: ['127.0.0.1:1883:1883/tcp']
    cap_drop: [all]
    security_opt: [no-new-privileges]
    cpus: 0.4
    mem_limit: 32M
  client:
    build: .
    image: fphammerle/wireless-sensor-mqtt
    #volumes:
    #- config:/etc/wireless-sensor-mqtt:ro
    command: wireless-sensor-mqtt
      --mqtt-host broker
      --mqtt-disable-tls
    #  --mqtt-username raspberrypi
    #  --mqtt-password-file /etc/wireless-sensor-mqtt/mqtt-password
    #  --mock-measurements
    #  --debug
    devices: [/dev/spidev0.0]
    read_only: true
    cap_drop: [all]
    security_opt:
    - no-new-privileges
    # docker-compose >=2.2,<3
    cpus: 0.4
    mem_limit: 32M

# https://docs.docker.com/compose/compose-file/compose-file-v2/
