# sync with https://github.com/fphammerle/docker-onion-service/blob/master/.github/workflows/container-image.yml

name: container image

on:
  push:
  pull_request:
  schedule:
  - cron: '0 20 * * 5'

jobs:
  docker-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: docker/setup-qemu-action@v3.2.0
    - uses: docker/setup-buildx-action@v3.7.1
    # > By default, this action uses the Git context so you don't need to use
    # > the actions/checkout action to checkout the repository because this
    # > will be done directly by buildkit. [...]
    # > any file mutation in the steps that precede [...] will be ignored,
    # > including processing of the .dockerignore file
    # https://github.com/marketplace/actions/build-and-push-docker-images
    # > The commit history is not preserved.
    # https://docs.docker.com/engine/reference/commandline/build/#git-repositories
    - uses: docker/build-push-action@v6.9.0
      with:
        build-args: | # git history unavailable (see above)
          SETUPTOOLS_SCM_PRETEND_VERSION=0
        platforms: |
          linux/amd64
          linux/arm64
  # long build time as numpy does not provide wheel for armv7
  docker-build-armv7:
    runs-on: ubuntu-20.04
    steps:
    - uses: docker/setup-qemu-action@v3.2.0
    - uses: docker/setup-buildx-action@v3.7.1
    - uses: docker/build-push-action@v6.9.0
      with:
        build-args: SETUPTOOLS_SCM_PRETEND_VERSION=0
        platforms: linux/arm/v7
